name:  Analyze, build and deploy
on: [push,pull_request]
jobs:

  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.0'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
  
  drive_android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 29]
        target: [default]
    needs: test
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.0'
          channel: 'stable'
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: flutter drive --target=test_driver/app.dart

  build_deploy:
    if: github.event_name != 'pull_request'
    runs-on: windows-latest
    needs: [drive_android,test]
    name: Build Release APK File
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.0'
          channel: 'stable'
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: flutter  config --enable-linux-desktop
      - run: flutter  config --enable-macos-desktop
      - run: flutter  config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows --release
      - run: flutter build apk --debug --split-per-abi
      - name: Create a Release APK and Windows Destop App
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk,build/windows/Build/Products/Release/*.app"
          token: ${{ secrets.GITHUB_TOKEN }}